app/user/forms.py
# -*- coding: utf-8 -*-
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileRequired, FileAllowed
from wtforms import StringField, TextAreaField, SubmitField, PasswordField, \
    BooleanField, FileField, HiddenField
from wtforms.validators import DataRequired, Length, Regexp, Optional, \
    ValidationError, EqualTo

from app.models import User


class EditProfileForm(FlaskForm):
    name = StringField('姓名', validators=[DataRequired(), Length(1, 30)])
    username = StringField('用户名',
                           validators=[DataRequired(), Length(1, 20),
                                       Regexp('^[a-zA-Z0-9]*$',
                                              message='用户名只能包含数字、字母')])
    bio = TextAreaField('简介', validators=[Optional(), Length(0, 120)])
    submit = SubmitField('修改')

    def validate_username(self, field):
        if field.data != current_user.username and User.query.filter_by(
                username=field.data).first():
            raise ValidationError('该用户名已被使用。')


class UploadAvatarForm(FlaskForm):
    image = FileField('上传图片', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], '图片格式只能是 .jpg 或 .png 文件')
    ])
    submit = SubmitField('提交')


class CropAvatarForm(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('裁截并更新')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('旧密码', validators=[DataRequired()])
    password = PasswordField('新密码', validators=[
        DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('确认密码', validators=[DataRequired()])
    submit = SubmitField('修改')


class PrivacySettingForm(FlaskForm):
    public_collections = BooleanField('公开我的收藏')
    submit = SubmitField('修改')


class DeleteAccountForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(), Length(1, 20)])
    submit = SubmitField('确认')

    def validate_username(self, field):
        if field.data != current_user.username:
            raise ValidationError('错误的用户名')

app/user/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bp = Blueprint('user', __name__)

from app.user import routes

app/user/routes.py
# -*- coding: utf-8 -*-
from flask import request, current_app, render_template, flash, redirect, \
    url_for
from flask_login import login_required, current_user, fresh_login_required, \
    logout_user
from sqlalchemy import func

from app import db, avatars
from app.decorators import permission_required
from app.models import User, Post, Category, categorizing, Collect, Comment
from app.user import bp
from app.user.forms import EditProfileForm, ChangePasswordForm, \
    PrivacySettingForm, DeleteAccountForm, UploadAvatarForm, CropAvatarForm
from app.utils import redirect_back


@bp.route('/<username>', methods=['GET'])
def index(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    category_id = request.args.get('category_id', None, type=int)
    per_page = current_app.config['SHMUBLOG_POST_PER_PAGE']
    if category_id:
        pagination = Post.query.with_parent(user) \
            .filter(Post.categories.any(id=category_id)) \
            .order_by(Post.timestamp.desc()).paginate(page, per_page)
    else:
        pagination = Post.query.with_parent(user).order_by(
            Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items

    # TODO: 考虑优化查询
    count_categories = db.session.query(Category.id, Category.name,
                                        func.count(Category.id).label('total')) \
        .join(categorizing).filter(categorizing.c.category_id == Category.id) \
        .join(Post).filter(Post.id == categorizing.c.post_id,
                           Post.author_id == user.id) \
        .group_by(Category.id) \
        .order_by(func.count(Category.id).desc()).all()
    return render_template('user/index.html', user=user, pagination=pagination,
                           posts=posts, categories=count_categories)


@bp.route('/follow/<username>', methods=['POST'])
@login_required
@permission_required('FOLLOW')
def follow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if current_user.is_following(user):
        flash(f'你已经关注过{user.username}了。', 'info')
        return redirect(url_for('user.index', username=username))

    current_user.follow(user)
    flash('关注成功。', 'success')
    return redirect_back()


@bp.route('/unfollow/<username>', methods=['POST'])
@login_required
@permission_required('UNFOLLOW')
def unfollow(username):
    user = User.query.filter_by(username=username).first_or_404()
    if not current_user.is_following(user):
        flash(f'你并没有关注{user.username}。', 'info')
        return redirect(url_for('user.index', username=username))

    current_user.unfollow(user)
    flash(f'取消了对{user.username}关注。', 'info')
    return redirect_back()


@bp.route('/<username>/followers')
def show_followers(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_USER_PER_PAGE']
    pagination = user.followers.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/followers.html', user=user,
                           pagination=pagination, follows=follows)


@bp.route('/<username>/following')
def show_following(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_USER_PER_PAGE']
    pagination = user.following.paginate(page, per_page)
    follows = pagination.items
    return render_template('user/following.html', user=user,
                           pagination=pagination, follows=follows)


@bp.route('/<username>/collections')
def show_collections(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_POST_PER_PAGE']
    pagination = Collect.query.with_parent(user).order_by(
        Collect.timestamp.desc()).paginate(page, per_page)
    collects = pagination.items
    return render_template('user/collections.html', user=user,
                           pagination=pagination, collects=collects)


@bp.route('/settings/profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.username = form.username.data
        current_user.bio = form.bio.data
        db.session.commit()
        flash('资料更新成功。', 'success')
        return redirect(url_for('.index', username=current_user.username))
    form.name.data = current_user.name
    form.username.data = current_user.username
    form.bio.data = current_user.bio
    return render_template('user/settings/edit_profile.html', form=form)


@bp.route('/settings/avatar')
@login_required
def change_avatar():
    upload_form = UploadAvatarForm()
    crop_form = CropAvatarForm()
    return render_template('user/settings/change_avatar.html',
                           upload_form=upload_form, crop_form=crop_form)


@bp.route('/settings/avatar/upload', methods=['POST'])
@login_required
@permission_required('UPLOAD')
def upload_avatar():
    form = UploadAvatarForm()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
        flash('图片已上传，请裁剪到合适尺寸。', 'success')
    return redirect(url_for('user.change_avatar'))


@bp.route('/settings/avatar/crop', methods=['POST'])
@login_required
def crop_avatar():
    form = CropAvatarForm()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像已更新。', 'success')
    return redirect(url_for('user.change_avatar'))


@bp.route('/settings/change-password', methods=['GET', 'POST'])
@fresh_login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.validate_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.commit()
            flash('密码已修改，请重新登陆。', 'success')
            logout_user()
            return redirect(url_for('auth.login'))
        else:
            flash('旧密码错误，请重新输入。', 'warning')
    return render_template('user/settings/change_password.html', form=form)


@bp.route('/settings/privacy', methods=['GET', 'POST'])
@login_required
def privacy_setting():
    form = PrivacySettingForm()
    if form.validate_on_submit():
        current_user.public_collections = form.public_collections.data
        db.session.commit()
        flash('设置成功。', 'success')
    form.public_collections.data = current_user.public_collections
    return render_template('user/settings/edit_privacy.html', form=form)


@bp.route('/settings/account/delete', methods=['GET', 'POST'])
@fresh_login_required
@permission_required('DELETE_ACCOUNT')
def delete_account():
    form = DeleteAccountForm()
    if form.validate_on_submit():
        db.session.delete(current_user._get_current_object())
        db.session.commit()
        logout_user()
        flash('好的，你自由了。', 'success')
        return redirect(url_for('main.index'))
    return render_template('user/settings/delete_account.html', form=form)


@bp.route('/management/posts')
@login_required
def manage_posts():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(current_user) \
        .order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('user/management/manage_posts.html',
                           pagination=pagination, posts=posts)


@bp.route('/management/comments')
@login_required
def manage_comments():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query \
        .filter(Comment.post_id.in_([post.id for post in current_user.posts])) \
        .order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('user/management/manage_comments.html',
                           pagination=pagination, comments=comments)

app/templates/user/settings/base.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% block content %}
    <div class="page-header">
        <h1>个人设置</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="nav nav-pills flex-column" role="tablist" aria-orientation="vertical">
                {{ render_nav_item('user.edit_profile', '编辑个人资料') }}
                {{ render_nav_item('user.change_avatar', '修改头像') }}
                {{ render_nav_item('user.change_password', '修改密码') }}
                {{ render_nav_item('user.privacy_setting', '隐私设置') }}
                {{ render_nav_item('user.delete_account', '删除账户') }}
            </div>
        </div>
        <div class="col-md-9">
            {% block setting_content %}{% endblock %}
        </div>
    </div>
{% endblock %}

app/templates/user/settings/change_avatar.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}修改头像{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/jquery.Jcrop.min.css') }}">
{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">修改头像</h3>
        <div class="card-body">
            {{ render_form(upload_form, action=url_for('user.upload_avatar')) }}
            <small class="text-muted">
                上传图像大小必须在 3MB 以内，文件类型只能是 .png 或 .jpg 格式。
            </small>
        </div>
        <div class="card-body">
            {{ avatars.preview_box('main.get_avatar', current_user.avatar_raw) }}
            {{ avatars.crop_box('main.get_avatar', current_user.avatar_raw) }}
        </div>
        <div class="card-body">
            {{ render_form(crop_form, action=url_for('user.crop_avatar')) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/jquery.Jcrop.min.js') }}"></script>
    {{ avatars.init_jcrop() }}
{% endblock %}

app/templates/user/settings/change_password.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}修改密码{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">修改密码</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/settings/delete_account.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}删除账户{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light border-danger">
        <h3 class="card-header">删除账户
            <span class="badge-danger badge badge-pill">警告：一旦删除将无法恢复！</span>
        </h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/settings/edit_privacy.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}隐私设置{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">隐私设置</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/user/settings/edit_profile.html
{% extends 'user/settings/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}编辑个人资料{% endblock %}

{% block setting_content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">编辑个人资料</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}