app/post/forms.py
# -*- coding: utf-8 -*-

from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, HiddenField
from wtforms.validators import DataRequired, Length, Optional, ValidationError

from app.models import Post


class PostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 60)])
    categories = StringField('分类（多个分类请用空格隔开）',
                             validators=[Optional(), Length(0, 64)])
    body = CKEditorField('内容', validators=[DataRequired()])
    submit = SubmitField('发表')


class EditPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 60)])
    categories = StringField('分类（多个分类请用空格隔开）',
                             validators=[Optional(), Length(0, 64)])
    body = CKEditorField('内容', validators=[DataRequired()])
    submit = SubmitField('修改')


class DeletePostForm(FlaskForm):
    id = HiddenField('博文编号')
    title = StringField('确认标题', validators=[DataRequired(), Length(1, 60)])
    submit = SubmitField('删除')

    def validate_title(self, field):
        post = Post.query.get_or_404(self.id.data)
        if self.title.data != post.title:
            raise ValidationError('输入标题错误')


class CommentForm(FlaskForm):
    body = TextAreaField('回复内容', validators=[DataRequired()])
    submit = SubmitField('提交')

app/post/__init__.py
# -*- coding: utf-8 -*-

from flask import Blueprint

bp = Blueprint('post', __name__)

from app.post import routes

app/post/routes.py
# -*- coding: utf-8 -*-
from flask import render_template, redirect, url_for, flash, request, \
    current_app, abort
from flask_login import login_required, current_user

from app.decorators import permission_required
from app.extensions import db
from app.models import Post, Category, Comment, User
from app.post import bp
from app.post.forms import PostForm, CommentForm, EditPostForm, DeletePostForm
from app.utils import redirect_back


@bp.route('/new', methods=['GET', 'POST'])
@login_required
@permission_required('PUBLISH')
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        post = Post(title=title, body=body, author=current_user)
        for category_name in form.categories.data.split():
            category = Category.query.filter_by(name=category_name).first()
            if category is None:
                category = Category(name=category_name)
                db.session.add(category)
                db.session.commit()

            if category not in post.categories:
                post.categories.append(category)
        db.session.add(post)
        db.session.commit()
        flash('博文发布成功。', 'success')
        return redirect(url_for('post.show_post', post_id=post.id))
    return render_template('post/new_post.html', form=form)


@bp.route('/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
@permission_required('PUBLISH')
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = EditPostForm()
    if form.validate_on_submit():
        title = form.title.data
        body = form.body.data
        post.title = title
        post.body = body
        for category_name in form.categories.data.split():
            category = Category.query.filter_by(name=category_name).first()
            if category is None:
                category = Category(name=category_name)
                db.session.add(category)
                db.session.commit()

            if category not in post.categories:
                post.categories.append(category)
        db.session.commit()
        flash('博文发布成功。', 'success')
        return redirect(url_for('post.show_post', post_id=post.id))

    form.title.data = post.title
    form.categories.data = ' '.join(
        [category.name for category in post.categories])
    form.body.data = post.body
    return render_template('post/edit_post.html', form=form)


@bp.route('/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    if current_user != post.author:
        abort(403)

    form = DeletePostForm()
    if form.validate_on_submit():
        db.session.delete(post)
        db.session.commit()
        flash('博文已删除。', 'success')
        return redirect(url_for('user.manage_posts'))
    form.id.data = post.id
    return render_template('post/delete_post.html', form=form)


@bp.route('/<int:post_id>/report', methods=['POST'])
@login_required
def report_post(post_id):
    post = Post.query.get_or_404(post_id)
    post.flag += 1
    db.session.commit()
    flash('举报成功。', 'success')
    return redirect_back()


@bp.route('/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    user = User.query.get_or_404(post.author_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['SHMUBLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post) \
        .order_by(Comment.timestamp.asc()) \
        .paginate(page, per_page)
    comments = pagination.items

    comment_form = CommentForm()

    # FIXME: 优化该逻辑
    if current_user != user:
        post.viewed += 1
        db.session.commit()

    return render_template('post/post.html', post=post, pagination=pagination,
                           comment_form=comment_form, comments=comments,
                           user=user)


@bp.route('/<int:post_id>/comment/new', methods=['POST'])
@login_required
@permission_required('COMMENT')
def new_comment(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    form = CommentForm()
    if form.validate_on_submit():
        body = form.body.data
        author = current_user._get_current_object()
        comment = Comment(body=body, author=author, post=post)

        replied_id = request.args.get('reply')
        if replied_id:
            comment.replied = Comment.query.get_or_404(replied_id)

        db.session.add(comment)
        db.session.commit()
        flash('评论发表成功。', 'success')
    return redirect(url_for('post.show_post', post_id=post_id, page=page))


@bp.route('/<int:post_id>/set_comment', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user != post.author:
        abort(403)

    if post.can_comment:
        post.can_comment = False
        flash('该博文已禁止评论。', 'info')
    else:
        post.can_comment = True
        flash('该博文已允许评论。', 'info')
    db.session.commit()
    return redirect(url_for('post.show_post', post_id=post_id))


@bp.route('/reply/comment/<int:comment_id>')
@login_required
@permission_required('COMMENT')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    return redirect(url_for('post.show_post',
                            post_id=comment.post_id, reply=comment_id,
                            author=comment.author.name) + '#comment-form')


@bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
@permission_required('DELETE_COMMENT')
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if current_user != comment.author and current_user != comment.post.author:
        abort(403)

    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除。', 'success')
    return redirect(url_for('user.manage_comments'))


@bp.route('/comment/<int:comment_id>/report', methods=['POST'])
@login_required
def report_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.flag += 1
    db.session.commit()
    flash('举报成功。', 'success')
    return redirect_back()


@bp.route('/<int:post_id>/collect', methods=['POST'])
@login_required
@permission_required('COLLECT')
def collect(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user.is_collecting(post):
        flash('你已收藏过了该博文。', 'info')
        return redirect(url_for('.show_post', post_id=post_id))

    current_user.collect(post)
    flash('博文已收藏。', 'success')
    return redirect(url_for('.show_post', post_id=post_id))


@bp.route('/<int:post_id>/uncollect', methods=['POST'])
@login_required
def uncollect(post_id):
    post = Post.query.get_or_404(post_id)
    if not current_user.is_collecting(post):
        flash('你并没有收藏过该博文。', 'info')
        return redirect(url_for('.show_post', post_id=post_id))

    current_user.uncollect(post)
    flash('已取消收藏该博文。', 'info')
    return redirect(url_for('.show_post', post_id=post_id))


@bp.route('/<int:post_id>/category/<int:category_id>', methods=['POST'])
@login_required
def delete_post_category(post_id, category_id):
    post = Post.query.with_parent(current_user) \
        .filter_by(id=post_id).first_or_404()
    if current_user != post.author:
        abort(403)

    category = Category.query.get_or_404(category_id)

    post.categories.remove(category)
    db.session.delete(category)
    db.session.commit()
    flash('博文类别已删除。', 'info')
    return redirect_back()

app/templates/post/_comment.html
<div class="comments col-md-12" id="comments">
    <h3>{{ post.comments|length }} 评论
        <small>
            <a href="{{ url_for('post.show_post', post_id=post.id, page=pagination.pages or 1) }}#comment-form">最新</a>
        </small>
        {% if current_user == post.author %}
            <form class="inline float-right" method="post"
                  action="{{ url_for('post.set_comment', post_id=post.id) }}">
                <input type="hidden" name="csrf_token"
                       value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-xs btn-link float-right">
                    {% if post.can_comment %}禁止{% else %}允许{% endif %}评论
                </button>
            </form>
        {% endif %}
    </h3>
    <hr>
    <div class="row">
        {% if comments %}
            {% for comment in comments %}
                <div class="col-md-12">
                    <div class="card mb-3">
                        <div class="row no-gutters">
                            <div class="col-md-2">
                                <a href="{{ url_for('user.index', username=comment.author.username) }}">
                                    <img class="card-img"
                                         src="{{ url_for('main.get_avatar', filename=comment.author.avatar_m) }}">
                                </a>
                            </div>
                            <div class="col-md-10">
                                <div class="card-body">
                                    <h5 class="card-title">
                                        <a href="{{ url_for('user.index', username=comment.author.username) }}">
                                            {{ comment.author.name }}
                                        </a>
                                        <small class="text-muted">
                                            发表于 {{ moment(comment.timestamp).fromNow(refresh=True) }}
                                        </small>
                                        {% if current_user.is_authenticated %}
                                            <span class="float-md-right">
                                            {% if current_user != comment.author %}
                                                <a class="btn"
                                                   href="{{ url_for('post.reply_comment', comment_id=comment.id) }}">
                                                    回复
                                                </a>
                                                <form class="inline"
                                                      method="post"
                                                      action="{{ url_for('post.report_comment', comment_id=comment.id, next=request.full_path) }}">
                                                    <input type="hidden"
                                                           name="csrf_token"
                                                           value="{{ csrf_token() }}">
                                                    <button type="submit"
                                                       class="btn btn-link">
                                                        举报
                                                    </button>
                                                </form>
                                            {% endif %}
                                            </span>
                                        {% endif %}
                                    </h5>
                                    <p class="card-text">
                                        {% if comment.replied %}
                                            <a href="{{ url_for('user.index', username=comment.replied.author.username) }}">
                                                @{{ comment.replied.author.name }}
                                            </a>:
                                        {% endif %}
                                        {{ comment.body }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <p class="tip">尚未有评论。</p>
        {% endif %}
    </div>
    <div class="row justify-content-md-center">
        {{ render_pagination(pagination) }}
    </div>

    {# 评论表单 #}
    <div class="row">
        <div class="col-md-12">
            {% if post.can_comment %}
                {% if current_user.is_authenticated %}
                    {% if current_user.can('COMMENT') %}
                        <div class="card mb-3 border-0">
                            <div class="row no-gutters">
                                <div class="col-md-2">
                                    <img class="card-img"
                                         src="{{ url_for('main.get_avatar', filename=current_user.avatar_m) }}">
                                </div>
                                <div class="col-md-10">
                                    <div class="card-body">
                                        <h5 class="card-title">
                                            <a href="{{ url_for('user.index', username=current_user.username) }}">
                                                {{ current_user.name }}
                                                <small class="text-muted">
                                                    {{ current_user.username }}
                                                </small>
                                            </a>
                                        </h5>
                                        {% if request.args.get('reply') %}
                                            <div class="alert alert-dark">
                                                @{{ request.args.get('author') }}:
                                                <a class="float-right"
                                                   href="{{ url_for('post.show_post', post_id=post.id) }}">取消</a>
                                            </div>
                                        {% endif %}
                                        <div class="comment-form"
                                             id="comment-form">
                                            {{ render_form(comment_form, action=url_for('post.new_comment', post_id=post.id, page=pagination.pages or 1, reply=request.args.get('reply')), extra_classes="text-right") }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% else %}
                        <p class="tip">
                            没有权限。
                        </p>
                    {% endif %}
                {% else %}
                    <p class="tip">
                        <a href="{{ url_for('auth.login') }}">登陆</a>
                        或
                        <a href="{{ url_for('auth.register') }}">注册</a> 后才能评论。
                    </p>
                {% endif %}
            {% else %}
                <p class="tip">
                    评论功能已被禁止。
                </p>
            {% endif %}
        </div>
    </div>
</div>

app/templates/post/delete_post.html
{% extends 'user/management/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}删除博文{% endblock %}

{% block management_content %}
    <div class="card w-100 bg-light border-danger">
        <h3 class="card-header">删除博文
            <span class="badge-danger badge badge-pill">警告：一旦删除将无法恢复！</span>
        </h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/post/edit_post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}编辑博文{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>编辑博文</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {# TODO: 到 ckeditor 官网定制编辑器到本地。 #}
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body') }}
{% endblock %}

app/templates/post/new_post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}新博文{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>新博文</h1>
    </div>
    {{ render_form(form) }}
{% endblock %}

{% block scripts %}
    {{ super() }}
    {# TODO: 到 ckeditor 官网定制编辑器到本地。 #}
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='body') }}
{% endblock %}

app/templates/post/post.html
{% extends 'user/base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block right_content %}
    <div class="page-header">
        <h1>{{ post.title }} </h1>
        <small>
            类别：
            {% if post.categories %}
                {% for category in post.categories %}
                    <a href="#">
                        {{ category.name }}
                    </a>
                {% endfor %}
            {% else %}
                <a>未分类</a>
            {% endif %}
            阅读数： {{ post.viewed }}
            发表于： {{ moment(post.timestamp).format('LLL') }}
        </small>
        {% if current_user.is_authenticated %}
            <div class="float-md-right">
                <div class="btn-group" role="group" aria-label="Basic example">
                    {% if current_user.is_admin %}
                        <form class="inline"
                              method="post"
                              action="{{ url_for('admin.delete_post', post_id=post.id, next=request.host_url) }}">
                            <input type="hidden" name="csrf_token"
                                   value="{{ csrf_token() }}">
                            <button type="submit"
                                    class="btn btn-outline-danger btn-sm mr-md-3">
                                删除
                            </button>
                        </form>
                    {% endif %}
                    {% if current_user != post.author %}
                        <form class="inline"
                              method="post"
                              action="{{ url_for('post.report_post', post_id=post.id, next=request.full_path) }}">
                            <input type="hidden" name="csrf_token"
                                   value="{{ csrf_token() }}">
                            <button type="submit"
                                    class="btn btn-outline-danger btn-sm mr-md-3">
                                举报
                            </button>
                        </form>
                    {% endif %}
                    {% if current_user.is_collecting(post) %}
                        <form class="inline" method="post"
                              action="{{ url_for('post.uncollect', post_id=post.id) }}">
                            <input type="hidden" name="csrf_token"
                                   value="{{ csrf_token() }}">
                            <button type="submit"
                                    class="btn btn-outline-secondary btn-sm">
                                取消收藏
                            </button>
                        </form>
                    {% else %}
                        <form class="inline" method="post"
                              action="{{ url_for('post.collect', post_id=post.id) }}">
                            <input type="hidden" name="csrf_token"
                                   value="{{ csrf_token() }}">
                            <button type="submit"
                                    class="btn btn-outline-primary btn-sm">
                                收藏
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% else %}
            <form class="inline float-md-right" method="post"
                  action="{{ url_for('post.collect', post_id=post.id) }}">
                <input type="hidden" name="csrf_token"
                       value="{{ csrf_token() }}">
                <button type="submit" class="btn btn-primary btn-sm">
                    <span class="oi oi-star"></span> 收藏
                </button>
            </form>
        {% endif %}
    </div>
    <hr>
    {{ post.body|safe }}
    <hr>
    <div class="row">
        {% include 'post/_comment.html' %}
    </div>
{% endblock %}